#!/usr/bin/env bash
# Create (or reuse) the Marketing Digest local container registry and wire it to Kind.
# Idempotent. Does NOT delete or recreate the Kind cluster.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_common.sh
source "${SCRIPT_DIR}/_common.sh"

configure_kind_insecure_registry() {
  local hosts_dir="/etc/containerd/certs.d/${KIND_REGISTRY_ENDPOINT}"
  local hosts_file="${hosts_dir}/hosts.toml"

  log "Configuring containerd hosts.toml on ${KIND_NODE} for insecure HTTP registry ${KIND_REGISTRY_ENDPOINT}"
  docker exec "${KIND_NODE}" mkdir -p "${hosts_dir}"
  docker exec -i "${KIND_NODE}" tee "${hosts_file}" >/dev/null <<EOF
# Generated by md-infra/lcr/setup.sh — plain HTTP local development registry (no TLS).
server = "http://${KIND_REGISTRY_ENDPOINT}"

[host."http://${KIND_REGISTRY_ENDPOINT}"]
  capabilities = ["pull", "resolve"]
  skip_verify = true
EOF

  log "containerd registry host config written for ${KIND_REGISTRY_ENDPOINT} (no Kind cluster recreate)"
}

connect_registry_to_kind_network() {
  local networks
  networks="$(docker inspect -f '{{range $k,$v := .NetworkSettings.Networks}}{{$k}} {{end}}' "${REGISTRY_NAME}")"
  if printf '%s' "${networks}" | grep -qw "${KIND_NETWORK}"; then
    log "Registry already attached to Docker network '${KIND_NETWORK}'"
  else
    log "Connecting ${REGISTRY_NAME} to Docker network '${KIND_NETWORK}'"
    docker network connect "${KIND_NETWORK}" "${REGISTRY_NAME}"
  fi
}

publish_registry_configmap() {
  # Optional discovery ConfigMap used by some Kind tooling (safe no-op if already present).
  if ! command -v kubectl >/dev/null 2>&1; then
    log "kubectl not found; skipping local-registry-hosting ConfigMap"
    return 0
  fi
  if ! kubectl config current-context 2>/dev/null | grep -q "kind-${KIND_CLUSTER}\|${KIND_CLUSTER}"; then
    log "kubectl context is not kind; skipping ConfigMap (current: $(kubectl config current-context 2>/dev/null || echo none))"
    return 0
  fi
  kubectl apply -f - <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-registry-hosting
  namespace: kube-public
data:
  localRegistryHosting.v1: |
    host: "${HOST_REGISTRY_ENDPOINT}"
    hostFromContainerRuntime: "${KIND_REGISTRY_ENDPOINT}"
    help: "https://github.com/Yuvraj02/md-infra/tree/main/lcr"
EOF
}

main() {
  require_cmd docker
  require_cmd kind
  select_docker_for_kind

  if ! kind get clusters 2>/dev/null | grep -qx "${KIND_CLUSTER}"; then
    die "Kind cluster '${KIND_CLUSTER}' not found (expected context kind-${KIND_CLUSTER})"
  fi
  if ! docker inspect "${KIND_NODE}" >/dev/null 2>&1; then
    die "Kind node container '${KIND_NODE}' not found"
  fi

  if docker inspect "${REGISTRY_NAME}" >/dev/null 2>&1; then
    log "Registry container '${REGISTRY_NAME}' already exists"
    local status
    status="$(docker inspect -f '{{.State.Status}}' "${REGISTRY_NAME}")"
    if [[ "${status}" != "running" ]]; then
      log "Starting existing registry container"
      docker start "${REGISTRY_NAME}" >/dev/null
    fi
  else
    log "Creating registry volume '${REGISTRY_VOLUME}' (if missing)"
    docker volume create "${REGISTRY_VOLUME}" >/dev/null

    log "Starting ${REGISTRY_NAME} (${REGISTRY_IMAGE}) on host port ${REGISTRY_HOST_PORT}"
    docker run -d \
      --name "${REGISTRY_NAME}" \
      --restart always \
      -p "${REGISTRY_HOST_PORT}:${REGISTRY_CONTAINER_PORT}" \
      -v "${REGISTRY_VOLUME}:/var/lib/registry" \
      "${REGISTRY_IMAGE}"
  fi

  connect_registry_to_kind_network
  configure_kind_insecure_registry
  publish_registry_configmap

  log "Waiting for registry HTTP API on ${HOST_REGISTRY_ENDPOINT}"
  local i
  for i in $(seq 1 30); do
    if curl -fsS "http://${HOST_REGISTRY_ENDPOINT}/v2/" >/dev/null 2>&1; then
      break
    fi
    sleep 1
    if [[ "${i}" -eq 30 ]]; then
      die "Registry HTTP API not reachable at http://${HOST_REGISTRY_ENDPOINT}/v2/"
    fi
  done

  log "Local registry ready"
  log "  Host push endpoint : ${HOST_REGISTRY_ENDPOINT}"
  log "  Kind pull endpoint  : ${KIND_REGISTRY_ENDPOINT}"
  log "  Example image      : $(kind_image gateway)"
}

main "$@"
